// Outbound links used across the site. Keep them in one place so the
// docs.gptme.org move only needs one edit.
export const links = {
  // docs.gptme.org is not live yet; the docs are still served at gptme.org/docs/.
  docs: "https://gptme.org/docs/",
  gettingStarted: "https://gptme.org/docs/getting-started.html",
  demos: "/readme/#-demos",
  github: "https://github.com/gptme/gptme",
  stats: "https://github.com/gptme/stats",
  // gptme project timeline (releases and milestones).
  timeline: "https://gptme.org/docs/timeline.html",
  // Bob's own timeline; generated by the TimeToBuildBob.github.io Jekyll site.
  bobTimeline: "https://timetobuildbob.github.io/timeline/",
  bob: "https://github.com/TimeToBuildBob",
  alice: "https://github.com/TimeToLearnAlice",
  agentTemplate: "https://github.com/gptme/gptme-agent-template",
  agents: "https://gptme.org/docs/agents.html",
  autonomous: "https://gptme.org/docs/agents/autonomous.html",
  discord: "https://discord.gg/NMaCmmkxWv",
  gptmeAi: "https://gptme.ai",
  cloudDocs: "https://gptme.org/docs/cloud.html",
  webui: "https://chat.gptme.org",
  downloads: "https://gptme.org/downloads/",
  vim: "https://github.com/gptme/gptme.vim",
  server: "https://gptme.org/docs/server.html",
  cli: "https://gptme.org/docs/usage.html",
  tui: "https://gptme.org/docs/tui.html",
  mcp: "https://gptme.org/docs/mcp.html",
  acp: "https://gptme.org/docs/acp.html",
  providers: "https://gptme.org/docs/providers.html",
  plugins: "https://gptme.org/docs/plugins.html",
  tools: "https://gptme.org/docs/tools.html",
  contrib: "https://github.com/gptme/gptme-contrib",
  superuserLabs: "https://superuserlabs.org",
} as const;
