from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

DEFAULT_TOOL_MANIFEST_PATH = Path("state/mcp-task-manifests.jsonl")
TOOL_MANIFEST_PATH_ENV = "GPTME_TOOL_MANIFEST_PATH"


@dataclass(frozen=True)
class TaskToolManifest:
    task_type: str
    tool_names: tuple[str, ...]
    path: Path


def _resolve_manifest_path(workspace: Path, manifest_path: Path | None = None) -> Path:
    if manifest_path is None:
        env_path = os.environ.get(TOOL_MANIFEST_PATH_ENV)
        manifest_path = Path(env_path) if env_path else DEFAULT_TOOL_MANIFEST_PATH

    manifest_path = manifest_path.expanduser()
    if not manifest_path.is_absolute():
        manifest_path = workspace / manifest_path
    return manifest_path


def _tool_name_from_record(tool: Any, *, line_no: int, task_type: str) -> str:
    if not isinstance(tool, dict):
        raise ValueError(
            f"Invalid tool manifest entry for {task_type!r} on line {line_no}: "
            "tool entries must be objects"
        )

    server_name = tool.get("server_name")
    tool_name = tool.get("tool_name")
    if not isinstance(server_name, str) or not server_name.strip():
        raise ValueError(
            f"Invalid tool manifest entry for {task_type!r} on line {line_no}: "
            "server_name must be a non-empty string"
        )
    if not isinstance(tool_name, str) or not tool_name.strip():
        raise ValueError(
            f"Invalid tool manifest entry for {task_type!r} on line {line_no}: "
            "tool_name must be a non-empty string"
        )

    return f"{server_name.strip()}.{tool_name.strip()}"


def load_task_manifest(
    task_type: str, workspace: Path, manifest_path: Path | None = None
) -> TaskToolManifest:
    """Load a task-specific MCP tool manifest from JSONL.

    The manifest format is generated by Bob's ``scripts/mcp-query.py
    --write-manifests``: one JSON object per line, each with ``task_type`` and a
    ``tools`` list containing ``server_name``/``tool_name`` pairs.
    """
    task_type = task_type.strip()
    if not task_type:
        raise ValueError("Task manifest type cannot be empty")

    path = _resolve_manifest_path(workspace, manifest_path)
    if not path.exists():
        raise FileNotFoundError(
            f"Tool manifest file not found: {path}. "
            f"Set {TOOL_MANIFEST_PATH_ENV} or run from a workspace with "
            f"{DEFAULT_TOOL_MANIFEST_PATH}."
        )

    available_task_types: list[str] = []
    with path.open(encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            if not line.strip():
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as e:
                raise ValueError(
                    f"Invalid JSON in tool manifest {path} on line {line_no}: {e}"
                ) from e
            if not isinstance(record, dict):
                raise ValueError(
                    f"Invalid tool manifest {path} on line {line_no}: record must be an object"
                )

            record_task_type = record.get("task_type")
            if isinstance(record_task_type, str):
                available_task_types.append(record_task_type)
            if record_task_type != task_type:
                continue

            tools = record.get("tools")
            if not isinstance(tools, list) or not tools:
                raise ValueError(
                    f"Invalid tool manifest for {task_type!r} on line {line_no}: "
                    "tools must be a non-empty list"
                )

            tool_names = tuple(
                dict.fromkeys(
                    _tool_name_from_record(tool, line_no=line_no, task_type=task_type)
                    for tool in tools
                )
            )
            return TaskToolManifest(
                task_type=task_type, tool_names=tool_names, path=path
            )

    available = ", ".join(sorted(set(available_task_types))) or "none"
    raise ValueError(
        f"Unknown tool manifest task type {task_type!r}. Available task types: {available}"
    )
