"""
Scaffold a persistent headless gptme agent as a systemd user service.

Generates the systemd unit(s), startup script, and skeleton config needed to
run a gptme agent on a timer — the pattern Bob uses for autonomous sessions —
without reverse-engineering an existing agent workspace.

Usage:
    gptme service init --name myagent --model gpt-4o-mini --work-dir ~/gptme-agent
    gptme service init --name myagent --timer-schedule hourly
    gptme service init --name myagent --output-dir ~/.config/systemd/user

The command writes files only; it does not install or start the service.
After generation, run:

    systemctl --user daemon-reload
    systemctl --user enable --now myagent.service   # or myagent.timer
"""

from __future__ import annotations

import logging
import re
import shlex
import subprocess
from pathlib import Path

import click

# Allowed characters for the agent name: matches systemd unit-name conventions.
_NAME_RE = re.compile(r"^[a-zA-Z0-9_-]+$")

logger = logging.getLogger(__name__)

# systemd disable/stop calls must not hang the CLI indefinitely.
_SYSTEMCTL_TIMEOUT_SEC = 30


def _escape_systemd_value(value: str) -> str:
    """Escape a value for safe interpolation into a systemd unit file.

    Doubles literal '%' so systemd doesn't expand it as a specifier (e.g. a
    work-dir of `/tmp/%h` would otherwise expand to the user's home dir), and
    rejects characters that systemd cannot represent safely in an executable
    path or that would terminate the current directive.
    """
    if "\n" in value or "\r" in value:
        raise click.BadParameter(
            f"{value!r} must not contain newlines (would corrupt the generated unit file)"
        )
    if any(char in value for char in ("\\", '"', "'")):
        raise click.BadParameter(
            f"{value!r} must not contain quotes or backslashes "
            "(unsupported in a systemd executable path)"
        )
    return value.replace("%", "%%")


def _escape_systemd_exec_value(value: str) -> str:
    """Escape a validated unit value for an ExecStart command line."""
    return _escape_systemd_value(value).replace("$", r"\x24")


SYSTEMD_SERVICE_TEMPLATE = """\
[Unit]
Description=gptme Autonomous Agent: {name}
Documentation=https://github.com/gptme/gptme#headless
After=network-online.target

[Service]
Type=simple
WorkingDirectory={work_dir}
Environment=GPTME_AGENT_NAME={name}
Environment="GPTME_AGENT_MODEL={model}"
Environment=GPTME_NON_INTERACTIVE=1
ExecStart=:"{exec_work_dir}/gptme-agent-run.sh"
StandardOutput=journal
StandardError=journal
Restart=on-failure
RestartSec=5
RestartMaxDelaySec=60

[Install]
WantedBy=default.target
"""

SYSTEMD_TIMER_TEMPLATE = """\
[Unit]
Description=gptme Autonomous Agent Timer: {name}

[Timer]
OnCalendar={schedule}
RandomizedDelaySec=60

[Install]
WantedBy=timers.target
"""

# OnCalendar expressions for the named schedules we support.
SCHEDULES: dict[str, str] = {
    "hourly": "*-*-* *:00:00",
    "daily": "*-*-* 00:00:00",
    "weekly": "Mon *-*-* 00:00:00",
}

STARTUP_SCRIPT_TEMPLATE = """\
#!/bin/bash
# gptme autonomous agent startup script.
# Generated by: gptme service init --name {name}
set -euo pipefail

AGENT_NAME="{name}"
WORK_DIR={work_dir}
JOURNAL_DIR="$WORK_DIR/journal/$(date +%Y-%m-%d)"

mkdir -p "$JOURNAL_DIR"
SESSION_ID=$(date +%Y%m%d-%H%M%S)
SESSION_LOG="$JOURNAL_DIR/session-$SESSION_ID.md"

# Durable session record placeholder. Replace the loop body with your
# agent's real work loop (CASCADE selector + task executor, etc.).
{{
  echo "# Session $SESSION_ID"
  echo
  echo "Agent: $AGENT_NAME"
  echo "Started: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
}} > "$SESSION_LOG"

echo "gptme agent {name}: wrote session log $SESSION_LOG"
"""

GPTME_TOML_TEMPLATE = """\
[agent]
name = "{name}"

[prompt]
files = [
  "AGENTS.md",
  "gptme.toml"
]

[lessons]
dirs = ["lessons", "skills"]
"""

AGENTS_MD_TEMPLATE = """\
# Agent Instructions for {name}

This file is auto-loaded by gptme and other agent runtimes.

## Role

{name} is a persistent headless gptme agent. It runs on a systemd timer and
executes its work loop non-interactively.

## Core Rules

### 1. Absolute Paths

Use `git rev-parse --show-toplevel` for the repo root.

### 2. Conventional Commits

- `feat:` — new feature
- `fix:` — bug fix
- `docs:` — documentation
- `refactor:` — code restructuring
- `test:` — tests
- `chore:` — maintenance

### 3. Stage Files Explicitly

Use `git add <files>`, never `git add .` or `git commit -a`.

### 4. Journal

Append-only logs in `journal/YYYY-MM-DD/`.
Never modify historical entries.
"""

HEALTH_CHECK_TEMPLATE = """\
#!/usr/bin/env python3
\"\"\"
Health check endpoint for {name} agent.

Checks systemd service status and returns JSON response.
Can be run standalone or wrapped in an HTTP server.

Usage:
    python3 health-check.py
    python3 health-check.py --json
\"\"\"

import json
import subprocess
from pathlib import Path
from datetime import datetime


def check_service_status(service_name: str) -> dict:
    \"\"\"Check systemd service status and return health info.\"\"\"
    try:
        result = subprocess.run(
            ["systemctl", "--user", "show", service_name, "-p", "State,ActiveState"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        lines = result.stdout.strip().split("\\n")
        state = next((l.split("=", 1)[1] for l in lines if l.startswith("State=")), "unknown")
        active = next((l.split("=", 1)[1] for l in lines if l.startswith("ActiveState=")), "unknown")

        return {{
            "service": service_name,
            "state": state,
            "active": active,
            "status": "healthy" if active == "active" else "unhealthy",
            "timestamp": datetime.utcnow().isoformat(),
        }}
    except Exception as e:
        return {{
            "service": service_name,
            "status": "error",
            "error": str(e),
            "timestamp": datetime.utcnow().isoformat(),
        }}


if __name__ == "__main__":
    import sys
    health = check_service_status("{name}")
    if "--json" in sys.argv or len(sys.argv) > 1:
        print(json.dumps(health, indent=2))
    else:
        print(f"Status: {{health['status']}} ({{health['active']}})")
        sys.exit(0 if health["status"] == "healthy" else 1)
"""

README_TEMPLATE = """\
# {name} Agent

Persistent headless gptme agent running on systemd.

## Starting the Service

```bash
# Reload systemd configuration
systemctl --user daemon-reload

# Enable and start (on-demand)
systemctl --user enable --now {name}.service

# Or if using a timer:
systemctl --user enable --now {name}.timer

# Follow logs in real-time
journalctl --user -u {name}.service -f
```

## Configuration

Edit `gptme.toml` to customize:
- Agent name
- Default model
- Lesson directories
- Prompt files

See `AGENTS.md` for operational guidelines.

## Health Check

To monitor the agent status:

```bash
curl http://localhost:8080/health
```

Response:
```json
{{
  "service": "{name}",
  "status": "healthy",
  "active": "active",
  "timestamp": "2026-08-22T18:00:00.000000"
}}
```

Or check via the health script:

```bash
python3 health-check.py
python3 health-check.py --json
```

## Logs

View service logs:

```bash
# Recent logs
journalctl --user -u {name}.service -n 50

# Follow logs in real-time
journalctl --user -u {name}.service -f

# Logs since a specific time
journalctl --user -u {name}.service --since "1 hour ago"
```

## Troubleshooting

### Service fails to start

1. Check syntax:
   ```bash
   systemctl --user status {name}.service
   ```

2. View detailed error:
   ```bash
   journalctl --user -u {name}.service -xe
   ```

3. Verify work directory exists:
   ```bash
   ls -la {work_dir}
   ```

### Timer doesn't trigger

1. Check timer is enabled:
   ```bash
   systemctl --user list-timers {name}.timer
   ```

2. Force a run:
   ```bash
   systemctl --user start {name}.service
   ```

## Stopping

```bash
# Stop the service
systemctl --user stop {name}.service

# Disable the timer
systemctl --user disable {name}.timer
```
"""


def _resolve_work_dir(work_dir: str) -> Path:
    """Resolve the agent work directory, creating it if needed."""
    path = Path(work_dir).expanduser().resolve()
    path.mkdir(parents=True, exist_ok=True)
    return path


def _write_file(path: Path, content: str, force: bool = False) -> bool:
    """Write a file, skipping existing files unless --force is set.

    Returns True if the file was written, False if skipped.
    """
    if path.exists() and not force:
        click.echo(f"  Skipped existing {path} (use --force to overwrite)")
        return False
    path.write_text(content)
    click.echo(f"  Created {path}")
    return True


@click.group(
    name="service",
    help="Manage persistent headless gptme agent services.",
    context_settings={"auto_envvar_prefix": "GPTME"},
)
def cli() -> None:
    """Persistent headless agent service scaffolding.

    Run `gptme service init` to scaffold a systemd user service for a
    headless gptme agent.
    """


@cli.command(
    name="init",
    help="Scaffold a systemd user service for a headless gptme agent.",
)
@click.option(
    "--name",
    "-n",
    type=str,
    required=True,
    help="Agent name (used for the service unit and agent identity).",
)
@click.option(
    "--model",
    "-m",
    type=str,
    default="gpt-4o-mini",
    show_default=True,
    help="Default model for the agent.",
)
@click.option(
    "--work-dir",
    "-d",
    type=str,
    default="~/gptme-agent",
    show_default=True,
    help="Agent work directory (created if missing).",
)
@click.option(
    "--output-dir",
    "-o",
    type=str,
    default="~/.config/systemd/user",
    show_default=True,
    help="Directory to write systemd units (usually ~/.config/systemd/user).",
)
@click.option(
    "--timer-schedule",
    type=click.Choice(["hourly", "daily", "weekly", "on-demand"]),
    default="daily",
    show_default=True,
    help="Timer schedule. 'on-demand' writes no timer (manual start only).",
)
@click.option(
    "--force",
    is_flag=True,
    help="Overwrite existing generated files.",
)
@click.option(
    "--enable-health-check",
    is_flag=True,
    help="Generate health-check.py and README.md with health endpoint documentation.",
)
def init(
    name: str,
    model: str,
    work_dir: str,
    output_dir: str,
    timer_schedule: str,
    force: bool,
    enable_health_check: bool,
) -> None:
    """Scaffold a systemd user service for a headless gptme agent.

    Generates, in the agent work directory:

        gptme.toml, AGENTS.md, gptme-agent-run.sh
        health-check.py, README.md          # if --enable-health-check

    and, in the systemd output directory:

        {name}.service             # main service unit
        {name}.timer               # optional periodic timer

    Example:

        \b
        gptme service init --name myagent --model gpt-4o-mini --work-dir ~/gptme-agent
        gptme service init --name myagent --enable-health-check
        systemctl --user daemon-reload
        systemctl --user enable --now myagent.timer
    """
    if not _NAME_RE.match(name):
        raise click.BadParameter(
            f"Name {name!r} contains invalid characters. "
            "Only letters, digits, hyphens, and underscores are allowed.",
            param_hint="'--name'",
        )

    work = _resolve_work_dir(work_dir)
    out_dir = Path(output_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    escaped_work_dir = _escape_systemd_value(str(work))
    escaped_exec_work_dir = _escape_systemd_exec_value(str(work))
    escaped_model = _escape_systemd_value(model)

    click.echo(f"Scaffolding headless agent '{name}'...")

    # Service unit
    _write_file(
        out_dir / f"{name}.service",
        SYSTEMD_SERVICE_TEMPLATE.format(
            name=name,
            model=escaped_model,
            work_dir=escaped_work_dir,
            exec_work_dir=escaped_exec_work_dir,
        ),
        force=force,
    )

    # Timer (skip for on-demand; remove stale timer only with --force)
    if timer_schedule == "on-demand":
        stale_timer = out_dir / f"{name}.timer"
        if stale_timer.exists():
            if force:
                # Disable the unit BEFORE removing the file so systemd can
                # resolve and stop the unit while the file is still present.
                click.echo(
                    f"  Disabling loaded timer unit {name}.timer (on-demand mode, --force)"
                )
                try:
                    result = subprocess.run(
                        ["systemctl", "--user", "disable", "--now", f"{name}.timer"],
                        check=False,  # best-effort; unit may not be enabled
                        timeout=_SYSTEMCTL_TIMEOUT_SEC,
                    )
                except OSError as exc:
                    click.echo(
                        f"  Warning: cannot run systemctl to disable {name}.timer: "
                        f"{exc}. Remove the timer file manually and run "
                        "'systemctl --user daemon-reload' to clear the unit.",
                        err=True,
                    )
                except subprocess.TimeoutExpired:
                    click.echo(
                        f"  Warning: systemctl --user disable --now {name}.timer "
                        f"timed out after {_SYSTEMCTL_TIMEOUT_SEC}s; leaving the "
                        "timer file in place. Disable it manually.",
                        err=True,
                    )
                else:
                    if result.returncode != 0:
                        click.echo(
                            f"  Warning: could not disable {name}.timer "
                            "(unit may not be enabled/loaded). "
                            "Periodic runs may continue until the next daemon-reload.",
                            err=True,
                        )
                    else:
                        stale_timer.unlink()
                        click.echo(f"  Removed stale timer file {stale_timer}")
            else:
                click.echo(
                    f"  Warning: existing timer {stale_timer} preserved (use --force to remove)."
                )
                click.echo(
                    "  The scheduled runs remain active until you disable the timer:"
                )
                click.echo(f"    systemctl --user disable --now {name}.timer")
    else:
        schedule = SCHEDULES.get(timer_schedule, SCHEDULES["daily"])
        _write_file(
            out_dir / f"{name}.timer",
            SYSTEMD_TIMER_TEMPLATE.format(name=name, schedule=schedule),
            force=force,
        )

    # Work directory contents
    _write_file(
        work / "gptme.toml",
        GPTME_TOML_TEMPLATE.format(name=name),
        force=force,
    )
    _write_file(
        work / "AGENTS.md",
        AGENTS_MD_TEMPLATE.format(name=name),
        force=force,
    )

    # Startup script
    startup = work / "gptme-agent-run.sh"
    _write_file(
        startup,
        STARTUP_SCRIPT_TEMPLATE.format(name=name, work_dir=shlex.quote(str(work))),
        force=force,
    )
    startup.chmod(0o755)

    # Health check (optional)
    if enable_health_check:
        health_script = work / "health-check.py"
        _write_file(
            health_script,
            HEALTH_CHECK_TEMPLATE.format(name=name),
            force=force,
        )
        health_script.chmod(0o755)

        # README
        _write_file(
            work / "README.md",
            README_TEMPLATE.format(name=name, work_dir=work),
            force=force,
        )

    click.echo()
    click.echo(f"✅ Initialized headless agent '{name}'")
    click.echo()
    click.echo("Next steps:")
    click.echo("  systemctl --user daemon-reload")
    if timer_schedule != "on-demand":
        click.echo(f"  systemctl --user enable --now {name}.timer")
    click.echo(f"  systemctl --user start {name}.service   # first run")
    click.echo(f"  journalctl --user -u {name}.service -f  # follow logs")


main = cli


if __name__ == "__main__":
    cli()
